version: "2.1"

services:
  consul:
    image: consul
    network_mode: host
  test-service:
    image: test-service
    build: .
    environment:
      NODE_ENV: production
    network_mode: host
    depends_on:
      - consul
